/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_opencv_androidstudio_NativeClass */

#ifndef _Included_com_example_ndk_opencv_androidstudio_NativeClass
#define _Included_com_example_ndk_opencv_androidstudio_NativeClass
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_zh_wang_android_opencv_ar_OpenCVARView_FindFeatures(JNIEnv* env, jobject thiz, jint width, jint height, jbyteArray yuv, jintArray bgra);

JNIEXPORT void JNICALL Java_zh_wang_android_opencv_ar_BitmapProcessing_GetCameraIntrisicParams(JNIEnv* env, jobject thiz);

JNIEXPORT void JNICALL Java_zh_wang_android_opencv_ar_Homography_doHomography(JNIEnv* env, jobject thiz, jstring filename);
#ifdef __cplusplus
}
#endif
#endif
